#!/user/bin/env groovy
//importing the shared library with its name defined in Jenkins. As we have a variable definition with groovy script we don't need the _ at the end of the library import  @Library('jenkins-shared-library')_
@Library('jenkins-shared-library')
def gv

pipeline {   
    agent any
    tools{
        maven 'maven-3.9'
    }

    stages{ 

       stage("init"){
             steps{
                 script{
                     gv = load "java-maven-app/script.groovy"    
                 }
              }
        }

          stage("build jar"){
             steps{
                 script{
                     buildJar()
                 }
              }
        }

         stage("build Image"){
                     steps{
                         script{
                             buildImage()
                         }
                     }
         }


        stage("deploy") {

             when {
                expression{
                    BRANCH_NAME == "main"                    
                }
                
            }
            steps {
                script {
                    gv.deployApp()
                }
            }
        }              
    }
} 
