#!/user/bin/env groovy
//importing the shared library with its name defined in Jenkins. As we have a variable definition with groovy script we don't need the _ at the end of the library import  @Library('jenkins-shared-library')_
//The line below is used to use the Global library defined in Jenkins system Global
//@Library('jenkins-shared-library')

//Define the library only for specific project

library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/lala-la-flaca/DevOpsBootcamp_8_Jenkins_SharedLibrary.git',
     credentialsId: 'github-credentials2'])

def gv

pipeline {   
    agent any
    tools{
        maven 'maven-3.9'
    }

    stages{ 

       stage("init"){
             steps{
                 script{
                     gv = load "java-maven-app/script.groovy"    
                 }
              }
        }

          stage("build jar"){
             steps{
                 script{
                     buildJar()
                 }
              }
        }

         stage("build and Push Image"){
                     steps{
                         script{
                             buildImage 'lala011/demo-app:jma-3.0'
                             dockerLogin()
                             dockerPush 'lala011/demo-app:jma-3.0'
                         }
                     }
         }


        stage("deploy") {

             when {
                expression{
                    BRANCH_NAME == "main"                    
                }
                
            }
            steps {
                script {
                    gv.deployApp()
                }
            }
        }              
    }
} 
