pipeline {   
    agent any
    tools{
        maven 'maven-3.9'
    }

    
    stages{    
        stage("build jar") {
                steps {
                    script{
                        echo "building the application..."
                        dir('java-maven-app') {
                            sh 'mvn package'
                        }
                   }
                }
        }
    
        stage("build image") {
                steps {
                    script{
                        echo "building the docker image..."
                        withCredentials([
                            usernamePassword(credentials: 'docker-hub-repo', usernameVariable: USER, passwordVariable: PWD)]){
                                dir('java-maven-app') {
                                    sh 'docker build -t lala011/demo-app:jma-2.0 .'
                                    sh 'echo $PWD | docker login -u $USER --password-stdin'
                                    sh 'docker push lala011/demo-app:jma-2.0' 
                                }                               
                            }
                       
                    }
                }
        }
                 
        
    
        stage("deploy") {
            steps {
                script {
                    echo "deploying the application"
                }
            }
        }              
    }
} 

